export const racks = [
    {
        id: "ae45jkl",
        columns: 6,
        rows: 6,
        bottles: [
            {
                id: "qqqsss",
                type: "rouge",
                domaine: "Chateau la pompe",
                aoc: "Grave",
                millesime: 2019,
                achat: 2023,
            },
            {
                id: "rrrttt",
                type: "rouge",
                domaine: "Chateau la pompe",
                aoc: "bordeaux",
                millesime: 2019,
                achat: 2023,
            },
            {
                id: "lllmmm",
                type: "blanc",
                domaine: "Montlouis",
                aoc: "Montlouis",
                millesime: 2017,
                achat: 2020,
            },
            {
                id: "vvvbbb",
                type: "blanc",
                domaine: "Montlouis",
                aoc: "Montlouis",
                millesime: 2017,
                achat: 2020,
            },
            {
                id: "oiughj",
                type: "rose",
                domaine: "piquette",
                aoc: "cote du rhone",
                millesime: 2022,
                achat: 2022,
            },
            {
                id: "oiughj",
                type: "rose",
                domaine: "piquette",
                aoc: "cote du rhone",
                millesime: 2022,
                achat: 2022,
            },
            {
                id: "oiughj",
                type: "rose",
                domaine: "piquette",
                aoc: "cote du rhone",
                millesime: 2022,
                achat: 2022,
            },
            {
                id: "",
                type: "",
                domaine: "",
                aoc: "",
                millesime: null,
                achat: null,
            },
            {
                id: "",
                type: "",
                domaine: "",
                aoc: "",
                millesime: null,
                achat: null,
            },
            {
                id: "",
                type: "",
                domaine: "",
                aoc: "",
                millesime: null,
                achat: null,
            },
            {
                id: "",
                type: "",
                domaine: "",
                aoc: "",
                millesime: null,
                achat: null,
            },
            {
                id: "",
                type: "",
                domaine: "",
                aoc: "",
                millesime: null,
                achat: null,
            },
        ]
    },
    {
        id: "xx99ppp",
        columns: 6,
        rows: 12,
        bottles: [
            {
                id: "",
                type: "petillant",
                domaine: "Nuit saint george",
                aoc: "champagne",
                millesime: 2019,
                achat: 2023,
            },
            {
                id: "",
                type: "petillant",
                domaine: "Nuit saint george",
                aoc: "champagne",
                millesime: 2019,
                achat: 2023,
            },
            {
                id: "",
                type: "petillant",
                domaine: "Nuit saint george",
                aoc: "champagne",
                millesime: 2019,
                achat: 2023,
            },
        ]
    },
    {
        id: "ae45jkl",
        columns: 6,
        rows: 12,
        bottles: [
            {
                id: "",
                type: "petillant",
                domaine: "tres cher",
                aoc: "Champagne",
                millesime: 2019,
                achat: 2023,
            },
            {
                id: "",
                type: "petillant",
                domaine: "Piquette",
                aoc: "mouseux",
                millesime: 2019,
                achat: 2023,
            },
            {
                id: "",
                type: "petillant",
                domaine: "Piquette",
                aoc: "mouseux",
                millesime: 2019,
                achat: 2023,
            },
        ]
    }
]
